/**
 * ============================================================
 *  BASE DE DATOS DE LA CLÍNICA
 *  >>> ESTE ES EL ÚNICO ARCHIVO QUE NECESITAS EDITAR <<<
 * ============================================================
 *  Reglas:
 *   - "palabrasClave" son las palabras que el paciente puede escribir.
 *     Escríbelas en minúscula y sin tildes (el bot normaliza el texto).
 *   - Si un dato no existe, NO lo inventes: déjalo fuera y el bot
 *     derivará la consulta al personal automáticamente.
 * ============================================================
 */

// ---------- DATOS GENERALES ----------
const clinica = {
  nombre: 'Clínica Médica',
  horario: 'Lunes a Viernes de 8:00 am a 5:00 pm | Sábados de 8:00 am a 12:00 m',
  direccion: null, // Ej: 'Av. Principal, Torre Médica, Piso 1'
  telefonoGeneral: null, // Ej: '+58 212-XXXXXXX'
};

// ---------- 1. SERVICIOS Y ESTUDIOS ----------
const servicios = [
  {
    nombre: 'ECO (Ecografía)',
    precio: '$40',
    telefono: '+58 424-2128645',
    palabrasClave: ['eco', 'ecografia', 'ecograma', 'ultrasonido', 'eco abdominal'],
    nota: null, // Ej: 'Debe venir en ayunas de 6 horas'
  },

  /* ---- PLANTILLA: copia este bloque para agregar más servicios ----
  {
    nombre: 'RAYOS X',
    precio: '$35',
    telefono: '+58 412-XXXXXXX',
    palabrasClave: ['rayos x', 'radiografia', 'placa'],
    nota: null,
  },
  ------------------------------------------------------------------ */
];

// ---------- 2. ESPECIALIDADES Y DOCTORES ----------
const especialidades = [
  {
    nombre: 'ANESTESIOLOGÍA',
    doctor: 'Dra. Xiomara Nuñez',
    telefono: '+584242572135',
    ubicacion: null,
    precio: null,
    palabrasClave: ['anestesia', 'anestesiologo', 'xiomara', 'nunez'],
    horario: null,
  },
  {
    nombre: 'CARDIOLOGÍA',
    doctor: 'Dr. Alexander Hernández',
    telefono: '+584142552814',
    ubicacion: 'Consultorio 901, PISO 9',
    precio: null,
    palabrasClave: ['cardiologia', 'cardiologo', 'corazon', 'alexander', 'hernandez'],
    horario: null,
  },
  {
    nombre: 'CARDIOLOGÍA',
    doctor: 'Dra. Maria Alejandra Jaimes',
    telefono: '+584149470153',
    ubicacion: 'CARDIO P3',
    precio: null,
    palabrasClave: ['cardiologia', 'cardiologo', 'corazon', 'maria', 'alejandra'],
    horario: null,
  },
  {
    nombre: 'CARDIOLOGÍA',
    doctor: 'Dra. Aura Fernandez',
    telefono: '+584241762695',
    ubicacion: 'CARDIO P3, PISO 3',
    precio: null,
    palabrasClave: ['cardiologia', 'cardiologo', 'corazon', 'aura', 'fernandez'],
    horario: null,
  },
  {
    nombre: 'CARDIOLOGÍA',
    doctor: 'Dr. Jhonny Ramirez',
    telefono: '+584149900181',
    ubicacion: 'CARDIO P3, PISO 3',
    precio: null,
    palabrasClave: ['cardiologia', 'cardiologo', 'corazon', 'jhonny', 'ramirez'],
    horario: null,
  },
  {
    nombre: 'CARDIOLOGÍA',
    doctor: 'Dra Genesis Rodriguez',
    telefono: '+584142972086',
    ubicacion: 'CARDIO P3, PISO 3',
    precio: null,
    palabrasClave: ['cardiologia', 'cardiologo', 'corazon', 'genesis', 'rodriguez'],
    horario: null,
  },
  {
    nombre: 'CARDIOLOGÍA',
    doctor: 'Dra Francheska Rodriguez',
    telefono: '+584144747550',
    ubicacion: 'CARDIO P3, PISO 3',
    precio: null,
    palabrasClave: ['cardiologia', 'cardiologo', 'corazon', 'francheska', 'rodriguez'],
    horario: null,
  },
  {
    nombre: 'CIRUGÍA GENERAL',
    doctor: 'Dra. Yelitza Manrique',
    telefono: '+584241105401',
    ubicacion: 'Consultorio 104, PISO 10',
    precio: null,
    palabrasClave: ['cirugia', 'cirugia general', 'cirujano', 'yelitza', 'manrique'],
    horario: null,
  },
  {
    nombre: 'CIRUGÍA GENERAL',
    doctor: 'Dra. Marellys Matheus',
    telefono: '+584247677556',
    ubicacion: 'Consultorio 806, PISO 8',
    precio: null,
    palabrasClave: ['cirugia', 'cirugia general', 'cirujano', 'marellys', 'matheus'],
    horario: null,
  },
  {
    nombre: 'CIRUGÍA ONCOLÓGICA',
    doctor: 'Dra. Pezzetti T, Lucía A. C.',
    telefono: null,
    ubicacion: 'Consultorio 705',
    precio: null,
    palabrasClave: ['cirugia oncologica', 'oncologo', 'pezzetti', 'lucia'],
    horario: null,
  },
  {
    nombre: 'CIRUGÍA ONCOLÓGICA',
    doctor: 'Dr. Carrasco P, Jesús A.',
    telefono: '+584166331980',
    ubicacion: 'Consultorio 704, PISO 7',
    precio: null,
    palabrasClave: ['cirugia oncologica', 'oncologo', 'carrasco', 'jesus'],
    horario: null,
  },
  {
    nombre: 'CIRUGÍA PEDIÁTRICA',
    doctor: 'Dr. González G. Rafael A.',
    telefono: '+584143255718',
    ubicacion: null,
    precio: null,
    palabrasClave: ['cirugia pediatrica', 'cirujano pediatrico', 'gonzalez', 'rafael'],
    horario: null,
  },
  {
    nombre: 'ANESTESIOLOGÍA',
    doctor: 'Dr. Ricardo Aguiar',
    telefono: '+584120254925',
    ubicacion: 'PISO 1',
    precio: null,
    palabrasClave: ['anestesia', 'anestesiologo', 'ricardo', 'aguiar'],
    horario: null,
  },
  {
    nombre: 'ANESTESIOLOGÍA',
    doctor: 'Dr Jean Malpica',
    telefono: '+584120254925',
    ubicacion: 'PISO 1',
    precio: null,
    palabrasClave: ['anestesia', 'anestesiologo', 'jean', 'malpica'],
    horario: null,
  },
  {
    nombre: 'ANESTESIOLOGÍA',
    doctor: 'Dra Alejandra Diaz',
    telefono: '+584241508216',
    ubicacion: 'PISO 1',
    precio: null,
    palabrasClave: ['anestesia', 'anestesiologo', 'alejandra', 'diaz'],
    horario: null,
  },
  {
    nombre: 'ANESTESIOLOGÍA',
    doctor: 'Dra. Evimar Perez',
    telefono: '+584243398237',
    ubicacion: 'PISO 1',
    precio: null,
    palabrasClave: ['anestesia', 'anestesiologo', 'evimar'],
    horario: null,
  },
  {
    nombre: 'NEFROLOGÍA',
    doctor: 'Dra. Yoynis Gonzalez',
    telefono: '+584243347093',
    ubicacion: 'PISO 1',
    precio: null,
    palabrasClave: ['nefrologia', 'nefrologo', 'yoynis', 'gonzalez'],
    horario: null,
  },
  {
    nombre: 'ANESTESIOLOGÍA',
    doctor: 'Dra Mileydi Rivera',
    telefono: '+584243186544',
    ubicacion: 'PISO 1',
    precio: null,
    palabrasClave: ['anestesia', 'anestesiologo', 'mileydi', 'rivera'],
    horario: null,
  },
  {
    nombre: 'ENDOCRINOLOGÍA',
    doctor: 'Dr. Camperos S. Paúl E.',
    telefono: '+584242932248',
    ubicacion: 'Consultorio 101, PISO 10',
    precio: null,
    palabrasClave: ['endocrinologia', 'endocrinologo', 'tiroides', 'camperos', 'paul'],
    horario: null,
  },
  {
    nombre: 'GASTROENTEROLOGÍA',
    doctor: 'Dr. Santiago D. Mario de J.',
    telefono: '+584126168774',
    ubicacion: 'Consultorio 302, PISO 3',
    precio: null,
    palabrasClave: ['gastroenterologia', 'gastroenterologo', 'gastro', 'santiago', 'mario'],
    horario: null,
  },
  {
    nombre: 'GINECOLOGÍA',
    doctor: 'Dr. Arocha A. Coromoto',
    telefono: null,
    ubicacion: 'Consultorio 605, PISO 3',
    precio: null,
    palabrasClave: ['ginecologia', 'ginecologo', 'gineco', 'obstetra', 'arocha', 'coromoto'],
    horario: null,
  },
  {
    nombre: 'GASTROENTEROLOGÍA',
    doctor: 'Dr. Orellana S. Simón E.',
    telefono: '+584163026360',
    ubicacion: 'Consultorio 306, PISO 3',
    precio: null,
    palabrasClave: ['gastroenterologia', 'gastroenterologo', 'gastro', 'orellana', 'simon'],
    horario: null,
  },
  {
    nombre: 'GINECOLOGÍA ONCOLÓGICA',
    doctor: 'Dra Johatson Freytez',
    telefono: '+584242527070',
    ubicacion: 'Consultorio 105',
    precio: null,
    palabrasClave: ['ginecologia oncologica', 'oncologo ginecologo', 'johatson', 'freytez'],
    horario: null,
  },
  {
    nombre: 'GINECOLOGÍA',
    doctor: 'Dra Samanta Rossi',
    telefono: '+584143517835',
    ubicacion: 'Consultorio 107, PISO 10',
    precio: null,
    palabrasClave: ['ginecologia', 'ginecologo', 'gineco', 'obstetra', 'samanta', 'rossi'],
    horario: null,
  },
  {
    nombre: 'GINECOLOGÍA',
    doctor: 'Dra. Mayerlin Fajardo',
    telefono: '+584141152651',
    ubicacion: 'Consultorio 107, PISO 10',
    precio: null,
    palabrasClave: ['ginecologia', 'ginecologo', 'gineco', 'obstetra', 'mayerlin', 'fajardo'],
    horario: null,
  },
  {
    nombre: 'GINECOLOGÍA',
    doctor: 'Dra. Arellano S. Alba J.',
    telefono: '+584129618669',
    ubicacion: 'Consultorio 707, PISO 7',
    precio: null,
    palabrasClave: ['ginecologia', 'ginecologo', 'gineco', 'obstetra', 'arellano', 'alba'],
    horario: null,
  },
  {
    nombre: 'GINECOLOGÍA',
    doctor: 'Dr. Segura B. Luis D.',
    telefono: '+584166206315',
    ubicacion: 'Consultorio 803, PISO 8',
    precio: null,
    palabrasClave: ['ginecologia', 'ginecologo', 'gineco', 'obstetra', 'segura'],
    horario: null,
  },
  {
    nombre: 'GINECOLOGÍA',
    doctor: 'Dr. Eduardo Reyes',
    telefono: '+584142773142',
    ubicacion: 'Consultorio 803, PISO 8',
    precio: null,
    palabrasClave: ['ginecologia', 'ginecologo', 'gineco', 'obstetra', 'eduardo'],
    horario: null,
  },
  {
    nombre: 'GINECOLOGÍA',
    doctor: 'Dr. Manuel Marin',
    telefono: '+584165386646',
    ubicacion: 'Consultorio 905, PISO 9',
    precio: null,
    palabrasClave: ['ginecologia', 'ginecologo', 'gineco', 'obstetra', 'marin'],
    horario: null,
  },
  {
    nombre: 'HEMATOLOGÍA',
    doctor: 'Dr. Inaty L. Joaquín J.',
    telefono: null,
    ubicacion: 'piso 4',
    precio: null,
    palabrasClave: ['hematologia', 'hematologo', 'sangre', 'inaty', 'joaquin'],
    horario: null,
  },
  {
    nombre: 'GINECOLOGÍA',
    doctor: 'Dr. Marín O, Manuel R.',
    telefono: '+584142505124',
    ubicacion: 'Consultorio 905, PISO 9',
    precio: null,
    palabrasClave: ['ginecologia', 'ginecologo', 'gineco', 'obstetra'],
    horario: null,
  },
  {
    nombre: 'GINECOLOGÍA ONCOLÓGICA',
    doctor: 'Dra Viviana Elisa',
    telefono: '+584146884575',
    ubicacion: 'Consultorio 105, PISO 10',
    precio: null,
    palabrasClave: ['ginecologia oncologica', 'oncologo ginecologo', 'viviana', 'elisa'],
    horario: null,
  },
  {
    nombre: 'MEDICINA INTERNA',
    doctor: 'Dr. Reyes H. Héctor José',
    telefono: null,
    ubicacion: 'Consultorio 101',
    precio: null,
    palabrasClave: ['internista', 'medicina interna', 'reyes', 'hector'],
    horario: null,
  },
  {
    nombre: 'HEMATOLOGÍA ONCOLÓGICA',
    doctor: 'Dra. Andrea Sanchez',
    telefono: '+584125444863',
    ubicacion: 'piso 4, PISO 4',
    precio: null,
    palabrasClave: ['hematologia oncologica', 'andrea', 'sanchez'],
    horario: null,
  },
  {
    nombre: 'MEDICINA INTENSIVA',
    doctor: 'Dr. Jose Pernalete',
    telefono: '+584166229538',
    ubicacion: 'PISO 1',
    precio: null,
    palabrasClave: ['intensivista', 'jose', 'pernalete'],
    horario: null,
  },
  {
    nombre: 'MEDICINA INTERNA',
    doctor: 'Dr. Vázquez G. Luis Manuel',
    telefono: '+584140140074',
    ubicacion: 'Consultorio 802, PISO 8',
    precio: null,
    palabrasClave: ['internista', 'medicina interna', 'vazquez', 'luis'],
    horario: null,
  },
  {
    nombre: 'MEDICINA INTERNA',
    doctor: 'Dra. Quiñones S. Maira E.',
    telefono: '+584166207877',
    ubicacion: 'Consultorio 906, PISO 9',
    precio: null,
    palabrasClave: ['internista', 'medicina interna', 'quinones', 'maira'],
    horario: null,
  },
  {
    nombre: 'REUMATOLOGÍA',
    doctor: 'Dra Josselyn Pazos',
    telefono: '+584249339654',
    ubicacion: 'Consultorio 703, PISO 7',
    precio: null,
    palabrasClave: ['reumatologia', 'reumatologo', 'reumas', 'josselyn', 'pazos'],
    horario: null,
  },
  {
    nombre: 'REUMATOLOGÍA',
    doctor: 'Dr. Marcos Prieto',
    telefono: '+584121445768',
    ubicacion: 'Consultorio 903, PISO 9',
    precio: null,
    palabrasClave: ['reumatologia', 'reumatologo', 'reumas', 'marcos', 'prieto'],
    horario: null,
  },
  {
    nombre: 'NEUMONOLOGÍA',
    doctor: 'Dr. Salazar B. Lisbeth C.',
    telefono: '+584166130136',
    ubicacion: 'Consultorio 801, PISO 8',
    precio: null,
    palabrasClave: ['neumonologia', 'neumonologo', 'pulmon', 'salazar', 'lisbeth'],
    horario: null,
  },
  {
    nombre: 'NEUROCIRUGÍA',
    doctor: 'Dr Franquis Samuel Herrera',
    telefono: '+584263054685',
    ubicacion: 'Consultorio 607, PISO 6',
    precio: null,
    palabrasClave: ['neurocirugia', 'neurocirujano', 'cerebro', 'franquis', 'samuel'],
    horario: null,
  },
  {
    nombre: 'NEUROCIRUGÍA',
    doctor: 'Dr Daniel Torres',
    telefono: '+584242606795',
    ubicacion: 'Consultorio 706, PISO 7',
    precio: null,
    palabrasClave: ['neurocirugia', 'neurocirujano', 'cerebro', 'daniel', 'torres'],
    horario: null,
  },
  {
    nombre: 'NEUROLOGÍA',
    doctor: 'Dr. López N., Arévalo Francisco',
    telefono: '+584166370511',
    ubicacion: 'Consultorio 701, PISO 7',
    precio: null,
    palabrasClave: ['neurologia', 'neurologo', 'cerebro', 'lopez', 'arevalo'],
    horario: null,
  },
  {
    nombre: 'PEDIATRÍA',
    doctor: 'Dr. Bermúdez B., Belkis C.',
    telefono: null,
    ubicacion: 'Consultorio 505',
    precio: null,
    palabrasClave: ['pediatria', 'pediatra', 'ninos', 'bermudez', 'belkis'],
    horario: null,
  },
  {
    nombre: 'ONCOLOGÍA',
    doctor: 'Dr. Manuel Serrano',
    telefono: '+584124830204',
    ubicacion: 'piso 4, PISO 4',
    precio: null,
    palabrasClave: ['oncologia', 'oncologo', 'cancer', 'quimioterapia', 'manuel', 'serrano'],
    horario: null,
  },
  {
    nombre: 'OTORRINOLARINGOLOGÍA',
    doctor: 'Dra. Ruiz Ruiz, Aida María',
    telefono: '+584143121194',
    ubicacion: 'Consultorio 106',
    precio: null,
    palabrasClave: ['otorrinolaringologia', 'otorrino', 'nariz', 'oido', 'ruiz'],
    horario: null,
  },
  {
    nombre: 'OTORRINOLARINGOLOGÍA',
    doctor: 'Dra Carmen Maria Artigas',
    telefono: '+584242018259',
    ubicacion: 'PB',
    precio: null,
    palabrasClave: ['otorrinolaringologia', 'otorrino', 'nariz', 'oido', 'carmen', 'maria'],
    horario: null,
  },
  {
    nombre: 'ALERGOLOGÍA',
    doctor: 'Dr. Oswaldo Perez',
    telefono: '+584126131474',
    ubicacion: 'Consultorio 506, PISO 5',
    precio: null,
    palabrasClave: ['alergologia', 'alergologo', 'alergia', 'oswaldo', 'perez'],
    horario: null,
  },
  {
    nombre: 'PEDIATRÍA',
    doctor: 'Dr. Maria Francia Rojas',
    telefono: '+584242741201',
    ubicacion: 'Consultorio 507, PISO 5',
    precio: null,
    palabrasClave: ['pediatria', 'pediatra', 'infectologia', 'maria', 'francia'],
    horario: null,
  },
  {
    nombre: 'PEDIATRÍA',
    doctor: 'Dra Edermary Nuñez',
    telefono: '+584246811400',
    ubicacion: 'Consultorio 506, PISO 5',
    precio: null,
    palabrasClave: ['pediatria', 'pediatra', 'neumologia', 'edermary', 'nunez'],
    horario: null,
  },
  {
    nombre: 'PEDIATRÍA',
    doctor: 'Dra. Kerlin Duran',
    telefono: '+584144199036',
    ubicacion: 'Consultorio 603, PISO 6',
    precio: null,
    palabrasClave: ['pediatria', 'pediatra', 'puericultura', 'kerlin', 'duran'],
    horario: null,
  },
  {
    nombre: 'NEFROLOGÍA PEDIÁTRICA',
    doctor: 'Dra. Franddie Vasquez',
    telefono: '+584166848307',
    ubicacion: 'Consultorio 504, PISO 5',
    precio: null,
    palabrasClave: ['nefrologia pediatrica', 'riñon', 'franddie', 'vasquez'],
    horario: null,
  },
  {
    nombre: 'TRAUMATOLOGÍA',
    doctor: 'Dra Yuliana Garcia',
    telefono: '+584247298658',
    ubicacion: 'Consultorio 606, PISO 6',
    precio: null,
    palabrasClave: ['traumatologia', 'traumatologo', 'ortopedia', 'huesos', 'yuliana', 'garcia'],
    horario: null,
  },
  {
    nombre: 'TRAUMATOLOGÍA',
    doctor: 'Dr. Pérez V. Nelson J.',
    telefono: '+584143228899',
    ubicacion: 'Consultorio 102, PISO 10',
    precio: null,
    palabrasClave: ['traumatologia', 'traumatologo', 'ortopedia', 'huesos', 'perez', 'nelson'],
    horario: null,
  },
  {
    nombre: 'TRAUMATOLOGÍA',
    doctor: 'Dr. Saddy Silva',
    telefono: '+584241937392',
    ubicacion: 'Consultorio 103, PISO 10',
    precio: null,
    palabrasClave: ['traumatologia', 'traumatologo', 'ortopedia', 'huesos', 'saddy', 'silva'],
    horario: null,
  },
  {
    nombre: 'TRAUMATOLOGÍA',
    doctor: 'Dra Carolina Alvarez',
    telefono: '+584149976190',
    ubicacion: 'Consultorio 804, PISO 8',
    precio: null,
    palabrasClave: ['traumatologia', 'traumatologo', 'ortopedia', 'huesos', 'carolina', 'alvarez'],
    horario: null,
  },
  {
    nombre: 'TRAUMATOLOGÍA',
    doctor: 'Dr. David Medina',
    telefono: '+584248684959',
    ubicacion: 'Consultorio 804',
    precio: null,
    palabrasClave: ['traumatologia', 'traumatologo', 'ortopedia', 'huesos', 'david', 'medina'],
    horario: null,
  },
  {
    nombre: 'UROLOGÍA',
    doctor: 'Dr. Ali Hamad Alkam',
    telefono: '+584127236283',
    ubicacion: 'Consultorio 906, PISO 9',
    precio: null,
    palabrasClave: ['urologia', 'urologo', 'riñon', 'ali', 'hamad'],
    horario: null,
  },
  {
    nombre: 'DERMATOLOGÍA',
    doctor: 'Dra Abril Sarmiento',
    telefono: '+584122525764',
    ubicacion: 'Consultorio 705, PISO 7',
    precio: null,
    palabrasClave: ['dermatologia', 'dermatologo', 'piel', 'abril', 'sarmiento'],
    horario: null,
  },
];

// ---------- 3. CONFIGURACIÓN DEL BOT ----------
const config = {
  // Número del personal que recibirá las consultas NO resueltas.
  // Formato internacional SIN "+", sin espacios ni guiones. null = desactivado.
  NUMERO_PERSONAL: null, // Ej: '584141234567'

  // Minutos tras los cuales se vuelve a saludar al mismo paciente.
  MINUTOS_PARA_SALUDAR_DE_NUEVO: 120,

  // Ignorar mensajes de grupos.
  IGNORAR_GRUPOS: true,

  // Frase de cierre (regla: siempre preguntar si se puede ayudar en algo más).
  CIERRE: '¿Puedo ayudarte con algo más? 😊',
};

module.exports = { clinica, servicios, especialidades, config };
