/**
 * ============================================================
 *  ESTUDIOS DE RADIOLOGÍA (imágenes) Y SUS PRECIOS
 * ============================================================
 *  Origen: "LISTADO Precios RADIOLOGIA.xlsx" -> pestaña "01-11-22"
 *  Precios en dólares ($).
 *
 *  NO EDITES ESTE ARCHIVO A MANO.
 *  Para actualizar los precios, reemplaza el Excel y ejecuta:
 *    node tools/generar-estudios.js
 * ============================================================
 */

const estudios = [
  { nombre: "Densitometría Columna Lumbar + 1 Fémur", tipo: "Densitometría", precio: "$20", nota: null },
  { nombre: "Densitometría Columna Lumbar + Ambos Fémur", tipo: "Densitometría", precio: "$20", nota: null },
  { nombre: "Densitometría Cuerpo Completo", tipo: "Densitometría", precio: "$20", nota: null },
  { nombre: "Morfometría", tipo: "Densitometría", precio: "$20", nota: null },
  { nombre: "Magnificación Bilateral", tipo: "Mamografía", precio: "$30", nota: null },
  { nombre: "Magnificación Unilateral", tipo: "Mamografía", precio: "$30", nota: null },
  { nombre: "Mamografía Bilateral", tipo: "Mamografía", precio: "$20", nota: null },
  { nombre: "Mamografía Bilateral con Prótesis", tipo: "Mamografía", precio: "$20", nota: null },
  { nombre: "Mamografía Unilateral", tipo: "Mamografía", precio: "$20", nota: null },
  { nombre: "Proyección Axilar Adicional", tipo: "Mamografía", precio: "$20", nota: null },
  { nombre: "Eco Abdominal", tipo: "Ecosonograma", precio: "$40", nota: "Venir en ayunas" },
  { nombre: "Eco Abdominopélvico", tipo: "Ecosonograma", precio: "$60", nota: "Venir en ayunas y con la vejiga llena" },
  { nombre: "Eco de Hombro", tipo: "Ecosonograma", precio: "$40", nota: null },
  { nombre: "Eco de Rodilla", tipo: "Ecosonograma", precio: "$40", nota: null },
  { nombre: "Eco Doppler Aorta Abdominal", tipo: "Ecosonograma", precio: "$50", nota: null },
  { nombre: "Eco Doppler Arterial o Venoso De Ms.Is", tipo: "Ecosonograma", precio: "$30", nota: "Precio por cada pierna (arterial o venoso)" },
  { nombre: "Eco Doppler Arterial o Venoso De Ms.Ss", tipo: "Ecosonograma", precio: "$30", nota: "Precio por cada brazo (arterial o venoso)" },
  { nombre: "Eco Doppler Arterial y Venoso de Ms.Is", tipo: "Ecosonograma", precio: "$50", nota: null },
  { nombre: "Eco Doppler Arterial y Venoso de Ms.Ss", tipo: "Ecosonograma", precio: "$50", nota: null },
  { nombre: "Eco Doppler Cadena Iliaca", tipo: "Ecosonograma", precio: "$50", nota: null },
  { nombre: "Eco Doppler Carotideo", tipo: "Ecosonograma", precio: "$50", nota: null },
  { nombre: "Eco Doppler de Partes Blandas", tipo: "Ecosonograma", precio: "$50", nota: null },
  { nombre: "Eco Doppler de Pene", tipo: "Ecosonograma", precio: "$50", nota: null },
  { nombre: "Eco Doppler de Pene + Ampolla Caverjet", tipo: "Ecosonograma", precio: "$65", nota: null },
  { nombre: "Eco Doppler Obstétrico", tipo: "Ecosonograma", precio: "$50", nota: null },
  { nombre: "Eco Doppler Pélvico", tipo: "Ecosonograma", precio: "$50", nota: null },
  { nombre: "Eco Doppler Renal", tipo: "Ecosonograma", precio: "$50", nota: null },
  { nombre: "Eco Doppler Testicular", tipo: "Ecosonograma", precio: "$50", nota: "A partir de los 2 años" },
  { nombre: "Eco Doppler Tiroideo", tipo: "Ecosonograma", precio: "$50", nota: null },
  { nombre: "Eco Doppler Transrectal de Próstata", tipo: "Ecosonograma", precio: "$60", nota: null },
  { nombre: "Eco Doppler Transvaginal", tipo: "Ecosonograma", precio: "$50", nota: null },
  { nombre: "Eco Esplenoportal", tipo: "Ecosonograma", precio: "$40", nota: null },
  { nombre: "Eco Fast", tipo: "Ecosonograma", precio: "$40", nota: null },
  { nombre: "Eco Genético del 1er Trimestre", tipo: "Ecosonograma", precio: "$40", nota: null },
  { nombre: "Eco Mamario", tipo: "Ecosonograma", precio: "$30", nota: "A partir de los 35 años, traer la última mamografía" },
  { nombre: "Eco Musculo-Esquelético", tipo: "Ecosonograma", precio: "$35", nota: null },
  { nombre: "Eco Obstétrico", tipo: "Ecosonograma", precio: "$40", nota: null },
  { nombre: "Eco Obstétrico 3D", tipo: "Ecosonograma", precio: "$40", nota: null },
  { nombre: "Eco Partes Blandas", tipo: "Ecosonograma", precio: "$40", nota: null },
  { nombre: "Eco Pélvico", tipo: "Ecosonograma", precio: "$40", nota: "Con la vejiga llena" },
  { nombre: "Eco Perfil Biofísico Fetal", tipo: "Ecosonograma", precio: "$40", nota: null },
  { nombre: "Eco Prostático", tipo: "Ecosonograma", precio: "$40", nota: "Con la vejiga llena" },
  { nombre: "Eco Punción de Tórax Guiada", tipo: "Ecosonograma", precio: "$100", nota: null },
  { nombre: "Eco Punción Guiada Con Aguja Fina en Mama", tipo: "Ecosonograma", precio: "$80", nota: null },
  { nombre: "Eco Punción Guiada Con Aguja Fina en Tiroides", tipo: "Ecosonograma", precio: "$80", nota: null },
  { nombre: "Eco Punción Guiada en Colecciones", tipo: "Ecosonograma", precio: "$60", nota: null },
  { nombre: "Eco Renal", tipo: "Ecosonograma", precio: "$40", nota: null },
  { nombre: "Eco Testicular", tipo: "Ecosonograma", precio: "$40", nota: "Solo hasta los 2 años" },
  { nombre: "Eco Tiroideo", tipo: "Ecosonograma", precio: null, nota: "No se realiza simple, se hace con Doppler" },
  { nombre: "Eco Toráxico", tipo: "Ecosonograma", precio: "$40", nota: null },
  { nombre: "Eco Transfontanelar", tipo: "Ecosonograma", precio: "$40", nota: null },
  { nombre: "Eco Transrectal de Próstata", tipo: "Ecosonograma", precio: "$40", nota: null },
  { nombre: "Eco Transvaginal", tipo: "Ecosonograma", precio: "$40", nota: null },
  { nombre: "Eco Vesical", tipo: "Ecosonograma", precio: "$40", nota: "Con medición de residuos post miccional" },
  { nombre: "Abdomen 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Abdomen 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: "Colangiografía trans Kehr: debe venir con su médico y los insumos" },
  { nombre: "Antebrazo 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Antebrazo 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "ATM 4 Proyecciones", tipo: "Rayos X", precio: "$50", nota: null },
  { nombre: "Cadera 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Cadera 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Cadera 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Calcáneo 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Calcáneo 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Calcáneo Ambos 2 Proyección", tipo: "Rayos X", precio: "$40", nota: null },
  { nombre: "Cara 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Cara 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Cara 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Cara 4 Proyecciones", tipo: "Rayos X", precio: "$30", nota: null },
  { nombre: "Clavícula 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Clavícula 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Clavícula Ambas 1 Proyección", tipo: "Rayos X", precio: "$30", nota: null },
  { nombre: "Clavícula Ambas 2 Proyecciones", tipo: "Rayos X", precio: "$40", nota: null },
  { nombre: "Codo 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Codo Ambos 2 Proyecciones", tipo: "Rayos X", precio: "$40", nota: null },
  { nombre: "Columna Cervical 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Columna Cervical 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Columna Cervical 4 Proyecciones", tipo: "Rayos X", precio: "$30", nota: null },
  { nombre: "Columna Cervical 5 Proyecciones", tipo: "Rayos X", precio: "$35", nota: null },
  { nombre: "Columna Cervical 6 Proyecciones", tipo: "Rayos X", precio: "$40", nota: null },
  { nombre: "Columna Cervical 7 Proyecciones", tipo: "Rayos X", precio: "$45", nota: null },
  { nombre: "Columna Dorsal 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Columna Dorsal 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Columna Dorsal 4 Proyecciones", tipo: "Rayos X", precio: "$30", nota: null },
  { nombre: "Columna Lumbo Sacra 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Columna Lumbo Sacra 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Columna Lumbo Sacra 4 Proyecciones", tipo: "Rayos X", precio: "$30", nota: null },
  { nombre: "Columna Lumbo Sacra 6 Proyecciones", tipo: "Rayos X", precio: "$40", nota: null },
  { nombre: "Columna Lumbo Sacra 7 Proyecciones", tipo: "Rayos X", precio: "$45", nota: null },
  { nombre: "Coxis 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Cráneo 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Cráneo 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Cráneo 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Dedos 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Dedos 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Edad Ósea", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Escafoides 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Escafoides 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Escafoides 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Escapula 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Escapula 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Escapula 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Esternón 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Fémur 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Fémur 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Fémur Ambos 1 Proyección", tipo: "Rayos X", precio: "$30", nota: null },
  { nombre: "Fémur Ambos 2 Proyecciones", tipo: "Rayos X", precio: "$40", nota: null },
  { nombre: "Hombro 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Hombro 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Hombro 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Hombro 4 Proyecciones", tipo: "Rayos X", precio: "$30", nota: null },
  { nombre: "Hombro 5 Proyecciones", tipo: "Rayos X", precio: "$35", nota: null },
  { nombre: "Hombros Ambos 1 Proyección", tipo: "Rayos X", precio: "$30", nota: null },
  { nombre: "Hombros Ambos 2 Proyecciones", tipo: "Rayos X", precio: "$40", nota: null },
  { nombre: "Hombros Ambos 3 Proyecciones", tipo: "Rayos X", precio: "$50", nota: null },
  { nombre: "Hombros Ambos 4 Proyecciones", tipo: "Rayos X", precio: "$60", nota: null },
  { nombre: "Hombros Ambos 5 Proyecciones", tipo: "Rayos X", precio: "$70", nota: null },
  { nombre: "Huesos Propios de Nariz 1 Proyección (Waters)", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Huesos Propios de Nariz 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Huesos Propios de Nariz 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Humero 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Humero 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Humero Ambos 1 Proyección", tipo: "Rayos X", precio: "$30", nota: null },
  { nombre: "Humero Ambos 2 Proyecciones", tipo: "Rayos X", precio: "$40", nota: null },
  { nombre: "Mano 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Mano 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Mano 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Manos Ambas 1 Proyección", tipo: "Rayos X", precio: "$30", nota: null },
  { nombre: "Manos Ambas 2 Proyecciones", tipo: "Rayos X", precio: "$40", nota: null },
  { nombre: "Manos Ambas 3 Proyecciones", tipo: "Rayos X", precio: "$50", nota: null },
  { nombre: "Maxilar 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Maxilar 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Maxilar 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Muñeca 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Muñeca 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Muñeca Dinámica 6 Proyecciones", tipo: "Rayos X", precio: "$40", nota: null },
  { nombre: "Muñecas Ambas 2 Proyecciones", tipo: "Rayos X", precio: "$40", nota: null },
  { nombre: "Muñecas Ambas 3 Proyecciones", tipo: "Rayos X", precio: "$50", nota: null },
  { nombre: "Muñecas Ambas Dinámica 6 Proyecciones", tipo: "Rayos X", precio: "$100", nota: null },
  { nombre: "Oído Medio", tipo: "Rayos X", precio: "$30", nota: null },
  { nombre: "Orbitas 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Orbitas 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Pelvis 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Pelvis 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Pelvis 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Pie 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Pie 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Pie Ambos 2 Proyecciones", tipo: "Rayos X", precio: "$40", nota: null },
  { nombre: "Pie Ambos 3 Proyecciones", tipo: "Rayos X", precio: "$50", nota: null },
  { nombre: "Pies con Apoyo", tipo: "Rayos X", precio: "$30", nota: null },
  { nombre: "Rinofaringe (Cavum) 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: "Boca abierta y boca cerrada" },
  { nombre: "Rodilla 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Rodilla 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Rodilla Ambas 2 Proyecciones", tipo: "Rayos X", precio: "$40", nota: null },
  { nombre: "Rodillas Ambas 1 Proyección", tipo: "Rayos X", precio: "$30", nota: null },
  { nombre: "Rotula 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Rotula 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Rotula 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Rotulas Ambas 1 Proyección", tipo: "Rayos X", precio: "$30", nota: null },
  { nombre: "Rotulas Ambas 2 Proyecciones", tipo: "Rayos X", precio: "$40", nota: null },
  { nombre: "Rotulas Ambas 3 Proyecciones", tipo: "Rayos X", precio: "$50", nota: null },
  { nombre: "Senos Paranasales", tipo: "Rayos X", precio: "$30", nota: null },
  { nombre: "Silla Turca 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Survey Óseo", tipo: "Rayos X", precio: "$180", nota: null },
  { nombre: "Test de Farril", tipo: "Rayos X", precio: "$55", nota: null },
  { nombre: "Tibia 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Tibias Ambas 2 Proyecciones", tipo: "Rayos X", precio: "$40", nota: null },
  { nombre: "Tobillo 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Tobillo 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Tobillo 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Tobillo Ambos 1 Proyección", tipo: "Rayos X", precio: "$30", nota: null },
  { nombre: "Tobillo Ambos 2 Proyecciones", tipo: "Rayos X", precio: "$40", nota: null },
  { nombre: "Tobillo Ambos 3 Proyecciones", tipo: "Rayos X", precio: "$50", nota: null },
  { nombre: "Tórax 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Tórax 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Tórax Óseo 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Tórax Óseo 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Tórax Óseo 3 Proyecciones", tipo: "Rayos X", precio: "$25", nota: null },
  { nombre: "Tórax Rayos Horizontales 1 Proyección", tipo: "Rayos X", precio: "$15", nota: null },
  { nombre: "Tórax Rayos Horizontales 2 Proyecciones", tipo: "Rayos X", precio: "$20", nota: null },
  { nombre: "Medición Tomografica de Miembros Inferiores", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Mielografía o Cisternografía", tipo: "Tomografía", precio: "$260", nota: null },
  { nombre: "Tac Abdomen", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Abdomino/ Pelvico", tipo: "Tomografía", precio: "$120", nota: null },
  { nombre: "Tac Antebrazo Bilateral", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Antebrazo Derecho", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Antebrazo Izquierdo", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Articulación Temporo Mandibular", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Brazo Bilateral", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Brazo Derecho", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Brazo Izquierdo", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Broncoscopia Virtual", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Cadera Bilateral", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Cadera Derecha", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Cadera Izquierda", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Calcio Coronario", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Cara", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Columna Cervical", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Columna Dorsal", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Columna Dorsal con Contraste", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Columna Lumbo Sacra", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Columna por Segundo", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Columna Sacro Coxis", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Cráneo", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Cráneo Ventana Ósea", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Cuello", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac de Codo Bilateral", tipo: "Tomografía", precio: "$80", nota: null },
  { nombre: "Tac de Codo Derecho", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac de Codo Izquierdo", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac de Rodillas con Contracción del Cuádriceps", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Fémur Bilateral", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Fémur Derecho", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Fémur Izquierdo", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Helicoidal", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Hígado", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Hombro Artografia Derecho", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Hombro Bilateral", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Hombro Derecho", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Hombro Izquierdo", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Macizo Facial", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Mano Bilateral", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Mano Derecha", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Mano Izquierda", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Maxilar", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Mielo Cervical", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Mielo Dorsal", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Mielo Lumbar", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Muñeca Bilateral", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Muñeca Derecha", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Muñeca Izquierda", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Oídos Axiales y Coronales", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Oídos Para Implante Coclear", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Orbitas Axiales y Coronales", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Pelvis", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Pelvis Ósea", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Pie Bilateral", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Pie Derecho", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Pie Izquierdo", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Pierna Bilateral", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Pierna Derecha", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Pierna Izquierda", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Protocolo de Litiasis", tipo: "Tomografía", precio: "$130", nota: null },
  { nombre: "Tac Reconstrucción 3D", tipo: "Tomografía", precio: "$110", nota: null },
  { nombre: "Tac Rodilla Derecha", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Rodilla Izquierda", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Rodillas Axiales (Hasta 3 Incid)", tipo: "Tomografía", precio: "$100", nota: null },
  { nombre: "Tac Rotula Alineación Patelo Femoral", tipo: "Tomografía", precio: "$100", nota: null },
  { nombre: "Tac Senos Paranasales Axiales", tipo: "Tomografía", precio: "$100", nota: null },
  { nombre: "Tac Senos Paranasales Axiales y Coronales", tipo: "Tomografía", precio: "$100", nota: null },
  { nombre: "Tac Senos Paranasales Coronales", tipo: "Tomografía", precio: "$100", nota: null },
  { nombre: "Tac Silla Turca", tipo: "Tomografía", precio: "$100", nota: null },
  { nombre: "Tac Tobillo Bilateral", tipo: "Tomografía", precio: "$100", nota: null },
  { nombre: "Tac Tobillo Derecho", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Tobillo Izquierdo", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Tórax", tipo: "Tomografía", precio: "$70", nota: null },
  { nombre: "Tac Tórax Alta Resolución", tipo: "Tomografía", precio: "$110", nota: null },
  { nombre: "Urotac", tipo: "Tomografía", precio: "$100", nota: null },
  { nombre: "Paquete Mujer (Eco Mamario + Densitometría + Mamografía)", tipo: "Paquete", precio: "$40", nota: null },
  { nombre: "Paquete Mujer (Eco Mamario + Mamografía)", tipo: "Paquete", precio: "$30", nota: null },
  { nombre: "Kit de Contraste E,V", tipo: "Contrastes", precio: "$250", nota: null },
  { nombre: "Kit de Contraste Oral", tipo: "Contrastes", precio: "$70", nota: "Más el costo del examen" },
  { nombre: "Tránsito Intestinal con Contraste Hidrosoluble", tipo: "Especiales", precio: "$60", nota: null },
  { nombre: "Digitalización", tipo: "Adicional", precio: "$2", nota: null },
  { nombre: "Kit de Materiales", tipo: "Adicional", precio: "$4", nota: null },
  { nombre: "Kit de Materiales con Contraste", tipo: "Adicional", precio: "$6", nota: null },
  { nombre: "Kit de Materiales Eco", tipo: "Adicional", precio: "$3", nota: null },
  { nombre: "Kit de RX", tipo: "Adicional", precio: "$5", nota: null },
  { nombre: "Placa", tipo: "Adicional", precio: "$2", nota: null },
  { nombre: "Reimpresión de Informe", tipo: "Adicional", precio: "$2", nota: null },
  { nombre: "Soporte Asistencial", tipo: "Adicional", precio: "$2", nota: null },
];

module.exports = { estudios };
